# You don't have to manually edit this file!
# RLBotGUI has an appearance editor with a nice colorpicker, database of items and more!
# To open it up, simply click the (i) icon next to your bot's name and then click Edit Appearance

[blue_loadout]
# Primary Color selection
team_color_id =  37
# Secondary Color selection
custom_color_id = 51
# Car type (Octane, Merc, etc)
car_id = 23
# Type of decal
decal_id = 0
# Wheel selection
wheels_id = 2715
# Boost selection
boost_id = 63
# Antenna Selection
antenna_id = 0
# Hat Selection
hat_id = 2728
# Paint Type (for first color)
paint_finish_id = 4127
# Paint Type (for secondary color)
custom_finish_id = 2275
# Engine Audio Selection
engine_audio_id = 10620
# Car trail Selection
trails_id = 1996
# Goal Explosion Selection
goal_explosion_id = 5287

[orange_loadout]
team_color_id = 34
custom_color_id = 59
car_id = 23
decal_id = 0
wheels_id = 2715
boost_id = 63
antenna_id = 0
hat_id = 2728
paint_finish_id = 4127
custom_finish_id = 2275
engine_audio_id = 10620
trails_id = 1996
goal_explosion_id = 5287

[blue_loadout.paint]
car_paint_id = 12
decal_paint_id = 0
wheels_paint_id = 0	
boost_paint_id = 12
antenna_paint_id = 0
hat_paint_id = 0
trails_paint_id = 0
goal_explosion_paint_id = 0

[orange_loadout.paint]
car_paint_id = 12
decal_paint_id = 0
wheels_paint_id = 0
boost_paint_id = 12
antenna_paint_id = 0
hat_paint_id = 0
trails_paint_id = 0
goal_explosion_paint_id = 0
